### ISSUE TITLE
What does Visual Object Retrieval mean

### ISSUE THREAD

**Issue by vpeopleonatank** [lannguyen0910/HydroViet_VOR#1]
I 'm learning about satellite image. Can you eloborate what does Visual Object Retrieval mean? Thank you.
[Edit] After googling, I get to know that VOR is something like searching image in an image database. I dont know what is your VOR project use case with satellite image? Can you give me some example?

**Comment by lannguyen0910** [comment]
Hi @vpeopleonatank. Sorry for my late reply, it's just a name of a project at my university. It's a humanitarian project about image retrieval. Here's the link with clear explanation and examples (first project in 5):
https://hackmd.io/@vodp/ryQ0yIouv

**Comment by vpeopleonatank** [comment]
Oh, these 're very good project applicable in countries. I 'm also a student in an university in North of Viet Nam. But I dont have chance to get these topic and application. Can I pm you on some social network to deliver you some question?

**Comment by lannguyen0910** [comment]
Sure, my FB account is: https://www.facebook.com/nguyen.hoang.lan.2000/
